
CREATE  TABLE MENU_ITEMS  (
    ID          NUMERIC(38,0)   NOT NULL,
    NAME        VARCHAR(512)    NOT NULL,
    DESCRIPTION VARCHAR(4000),
    URL         VARCHAR(4000),
    TARGET      VARCHAR(256),
    CONSTRAINT  MENU_ITMES_PK   PRIMARY KEY (ID)
);

CREATE  TABLE MENU_ROOTS (
    NAME        VARCHAR(512)    NOT NULL,
    ITEM_ID     NUMERIC(38,0)   NOT NULL,
    CONSTRAINT  MENU_ROOTS_PK   PRIMARY KEY (NAME),
    CONSTRAINT  ROOTS_FK        FOREIGN KEY (ITEM_ID) REFERENCES MENU_ITEMS(ID)
);

CREATE  TABLE MENU_RELATIONS (
    ITEM_ID         NUMERIC(38,0)       NOT NULL,
    CHILD_ITEM_ID   NUMERIC(38,0)       NOT NULL,
    ITEM_ORDER      NUMERIC(38,0)       NOT NULL,
    CONSTRAINT      RELATIONS_FK_ITEM   FOREIGN KEY (ITEM_ID)       REFERENCES MENU_ITEMS(ID),
    CONSTRAINT      RELATIONS_FK_CHILD  FOREIGN KEY (CHILD_ITEM_ID) REFERENCES MENU_ITEMS(ID)
);

CREATE  TABLE MENU_GROUPS (
    ITEM_ID     NUMERIC(38,0)   NOT NULL,
    ITEM_GROUP  VARCHAR(512)    NOT NULL,
    CONSTRAINT  GROUPS_FK_ITEM  FOREIGN KEY (ITEM_ID) REFERENCES MENU_ITEMS(ID)
);

CREATE  TABLE MENU_WINDOW_STATES (
    ITEM_ID         NUMERIC(38,0)   NOT NULL,
    WINDOW_STATE    VARCHAR(32)     NOT NULL,
    CONSTRAINT      STATES_FK_ITEM  FOREIGN KEY (ITEM_ID) REFERENCES MENU_ITEMS(ID)
);

CREATE  SEQUENCE MENU_ITEM_SEQ 
	MINVALUE 1 
	MAXVALUE 999999999999999999999999999
	START WITH  1
	INCREMENT BY  1
	CACHE 20;